import Banner from '@/components/Banner'
import Header from '@/components/Header'
import '../../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children, route
}: {
  children: React.ReactNode,
  route: string
}) {
  return (
    <html lang="en">
      <body className='max-w-7xl mx-auto'>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  )
}
